ascent_jet/ascent_jet/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^tinymce/', include('tinymce.urls')),
)

urlpatterns += patterns('',
    url(r'^$', 'common.views.index', name='index'),
    url(r'^about-us/contact/add/$', 'contact.views.contact_add', name='contact_add'),
    # override get-a-quote url (don't display Node details, but redirect to flights view)
    url(r'^get-a-quote/$', 'flights.views.get_a_qoute', name='get_a_qoute'),
    url(r'^', include('common.urls')),
    url(r'^common/', include('common.urls', namespace="common", app_name="common")),
    url(r'^flights/', include('flights.urls', namespace='flights', app_name='flights')),
    url(r'^', include('structure.urls', namespace='structure', app_name='structure')),
)

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ascent_jet/common/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('common.views',
    # url(r'^preview', 'preview', name='preview'),
    #url(r'^$', 'index', name='index'),

    url(r'^preview/(?P<appname>[-\w]+)/(?P<tname>[-\w]+)/$', 'show_template', name='show_template'),
    url(r'^preview/(?P<appname>[-\w\/]+)/', 'show_template', name='show_template'),
    url(r'^profile/', 'profile', name='profile'),
    url(r'^request/', 'offer_request', name='request'),
    url(r'^account/', 'account', name='account'),
)

ascent_jet/structure/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('structure.views',
	url(r'^(?P<slug>[-/\w]+)/$', 'node_detail', name='node_detail'),
)

ascent_jet/airplanes/models.py
from __future__ import absolute_import
from django.db import models
from django.utils.translation import ugettext_lazy as _

from common.models import Image


class AirplaneCategory(models.Model):
    title = models.CharField(_(u'title'), max_length=255)
    lead = models.TextField(_(u'lead'))
    image = models.ForeignKey(Image, verbose_name=_(u'image'))
    order = models.PositiveSmallIntegerField(_(u'order'), default=1, help_text="Define ordering of categories here. Use whole, positive numbers (1, 2, 3, ...).")
    hidden = models.BooleanField(_(u'hidden'), default=False, help_text="Use this checkbox to hide category in the frontend.")

    class Meta:
        ordering = ['order']
        verbose_name = 'airplane category'
        verbose_name_plural = 'airplane categories'

    def __unicode__(self):
        return self.title


class Airplane(models.Model):
    category = models.ForeignKey(AirplaneCategory, verbose_name=_(u'airplane category'), null=True, blank=True)
    title = models.CharField(_(u'title'), max_length=255)
    outer_image = models.ForeignKey(Image, verbose_name=_(u'outer image'), related_name='+')
    inner_image = models.ForeignKey(Image, verbose_name=_(u'inner image'), related_name='+', null=True, blank=True)
    layout_image = models.ForeignKey(Image, verbose_name=_(u'layout image'), related_name='+', null=True, blank=True)
    passenger_seating = models.CharField(_(u'passenger seating'), max_length=255, null=True, blank=True)
    luggage_capacity = models.CharField(_(u'luggage capacity'), max_length=255, null=True, blank=True)
    max_speed = models.CharField(_(u'max speed'), max_length=255, null=True, blank=True)
    max_range = models.CharField(_(u'max range'), max_length=255, null=True, blank=True)
    takeoff_distance = models.CharField(_(u'takeoff distance'), max_length=255, null=True, blank=True)
    max_altitude = models.CharField(_(u'max altitue'), max_length=255, null=True, blank=True)
    order = models.PositiveSmallIntegerField(_(u'order'), default=1, help_text="Define ordering of airplanes here. Use whole, positive numbers (1, 2, 3, ...).")

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return self.title

ascent_jet/contact/models.py
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(max_length=64, default="")
    email = models.EmailField(default="")
    message = models.CharField(max_length=2000, default="")
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "%s (%s)" % (self.first_name, self.email)

    def get_absolute_url(self):
        return '/about-us/contact/'

ascent_jet/structure/models.py
from __future__ import absolute_import
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy, reverse

from django_autoslug.fields import AutoSlugField
from mptt.models import MPTTModel, TreeForeignKey

from common.models import Image


class Article(models.Model):
    title = models.CharField(_(u'title'), max_length=255)
    lead = models.TextField(_(u'lead'))
    body = models.TextField(_(u'body'))
    image = models.ForeignKey(Image, verbose_name=_(u'image'), blank=True, null=True, help_text='Article image is inserted after article body text.')
    conclusion = models.TextField(_(u'conclusion'), blank=True, default='')
    node = models.ForeignKey('Node', null=True, help_text='Associate this article with a Node (Page).')
    order = models.PositiveSmallIntegerField(_(u'order'), default=1, help_text='If you have multiple articles per one Node (Page), you can define their order here.')

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('structure:node_detail', kwargs={'slug': self.node.slug})


class Node(MPTTModel):
    name = models.CharField(_(u'name'), max_length=255)
    image = models.ForeignKey(Image, verbose_name=_(u'header image'), blank=True, null=True)
    slug = AutoSlugField(_(u'slug'), populate_from=('name',), recursive='parent', use_recursive_slug=True, overwrite=True, editable=False, max_length=255, unique=True)
    visible = models.BooleanField(_(u'visible'), default=True)
    order = models.PositiveSmallIntegerField(_(u'order'), default=1)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', help_text='If this node is second-level navigation, select its parent here.')
    footer_group = models.ForeignKey('FooterGroup', blank=True, null=True)
    footer_group_order = models.PositiveSmallIntegerField(_(u'footer group order'), default=1)
    include_airplanes = models.BooleanField(_(u'include airplanes'), default=False, help_text='If checked, airplanes descriptions and categories will be included on the page.')

    class MPTTMeta:
        order_insertion_by = ('order',)

    class Meta:
        verbose_name = _('Node')
        verbose_name_plural = _('Nodes')
        ordering = ('order',)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('structure:node_detail', kwargs={'slug': self.slug})

    @property
    def sorted_article_set(self):
        return self.article_set.order_by('order')


class FooterGroup(models.Model):
    title = models.CharField(_(u'title'), max_length=255)

    def __unicode__(self):
        return self.title

    @property
    def sorted_node_set(self):
        return self.node_set.order_by('footer_group_order')

ascent_jet/structure/forms.py
from __future__ import absolute_import

from django import forms
from tinymce.widgets import TinyMCE

from .models import Article


class ArticleForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE)
    # override TinyMCE settings from settings.py with mce_attrs. Also, when overriding fields, you have to specify options like required and help text again.
    conclusion = forms.CharField(widget=TinyMCE(mce_attrs={'height': '150px'}), help_text='Conclusion is inserted below article main image and above footer.', required=False)

    class Meta:
        model = Article
        widgets = {
            # get normal size Text area, instead of default large one for Artice lead
            'lead': forms.Textarea,
        }
        exclude = ['id']

ascent_jet/structure/views.py
from __future__ import absolute_import
from django.views.generic.detail import DetailView

from airplanes.models import AirplaneCategory
from contact.forms import ContactForm
from .models import Node


class NodeDetail(DetailView):
    model = Node

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(NodeDetail, self).get_context_data(**kwargs)
        # Add in a QuerySet of airplane categories
        if self.get_object().include_airplanes:
            context['airplane_categories'] = AirplaneCategory.objects.filter(hidden=False)
        # add page title to context
        if self.object.sorted_article_set:
            try:
                context['page_title'] = self.object.sorted_article_set.all()[0].title
            except:
                pass
        # for contact page initialize form
        if self.get_object().pk == 13:
            context['form'] = ContactForm()
        return context

node_detail = NodeDetail.as_view()

ascent_jet/structure/templates/structure/node_detail.html
{% extends "preview/structure/base.html" %}
{% block title %}{{ page_title }} - Ascent Jet{% endblock %}

{% block content %}
<section class="image first article bottom-light-gray top-light-gray" style="background-image:url('{{ node.image.resource.url }}');"></section>
{% for article in node.sorted_article_set.all %}
<section class="image light-gray bottom-white">
  <div class="container">
    <div class="side">
      {% if subnavigation %}
      <ul class="nav">
        {% for sn in subnavigation %}
        <li {% if sn.slug in request.path %}class="active"{% endif %}><a href="/{{ sn.slug }}">{{ sn }}</a></li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="content">
      <h1>{{ article.title }}</h1>
      <p class="lead">
        {{ article.lead }}
      </p>
    </div>
  </div>
</section>
<section class="clean top-light-gray small-margin">
  <div class="container">
    <div class="content">
      {{ article.body | safe }}
    </div>
  </div>
</section>
{% if article.image %}
<section class="image both top-white plain bottom-white" style="background-image:url('{{ article.image.resource.url }}');"></section>
{% endif %}
{% if article.conclusion %}
<section class="clean top-light-gray small-margin">
  <div class="container">
    <div class="content">
      {{ article.conclusion | safe }}
    </div>
  </div>
</section>
{% endif %}
{% endfor %}

<!-- One of the nodes has attached airplane categories and airplanes descriptions -->
{% if airplane_categories %}
{% for category in airplane_categories %}
<section class="category clean">
  <div class="container">
    <h2>{{ category.title }}</h2>
    <div class="side">
      <figure>
        <img src="{{ category.image.get_thumb_400 }}">
        {% if category.image.caption %}
        <figcaption>{{ category.image.caption }}</figcaption>
        {% endif %}
        <figcaption></figcaption>
      </figure>
    </div>
    <div class="content">
      <p>
        {{ category.lead | safe }}
      </p>
      <h3>View aircraft</h3>
      <ul class="aircrafts">
        {% for airplane in category.airplane_set.all %}
        <li class="closed">
          <div class="title">
            {{ airplane.title }}
            <span class="icons icons-slide-down"></span>
            <span class="icons icons-slide-up"></span>
          </div>
          <div class="extra">
            <div class="gallery">
              <div class="gallery-img" style="background-image: url({{ airplane.outer_image.get_thumb_325 }});">
              </div>
              <div class="gallery-img" style="background-image: url({{ airplane.inner_image.get_thumb_325 }});">
              </div>
            </div>
            <div class="details">
              <h4>Aircraft Info</h4>
              <dl>
                {% if airplane.passenger_seating %}
                <dt>Passenger Seating:</dt>
                <dd>{{ airplane.passenger_seating }}</dd>
                {% endif %}
                {% if airplane.luggage_capacity %}
                <dt>Luggage Capacity:</dt>
                <dd>{{ airplane.luggage_capacity }}</dd>
                {% endif %}
                {% if airplane.max_speed %}
                <dt>Max. Cruise Speed:</dt>
                <dd>{{ airplane.max_speed }}</dd>
                {% endif %}
                {% if airplane.max_range %}
                <dt>Range:</dt>
                <dd>{{ airplane.max_range }}</dd>
                {% endif %}
                {% if airplane.takeoff_distance %}
                <dt>Takeoff distance:</dt>
                <dd>{{ airplane.takeoff_distance }}</dd>
                {% endif %}
                {% if airplane.max_altitude %}
                <dt>Max. Operating Altitude:</dt>
                <dd>{{ airplane.max_altitude }}</dd>
                {% endif %}
              </dl>
            </div>
            <div class="floorplan">
              <img src="{{ airplane.layout_image.get_thumb_325 }}">
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>
{% endfor %}
{% endif %}

<!-- CONTACT FORM -->
{% if node.pk == 13 %}
<section class="clean top-light-gray small-margin">
  <div class="container">
    <div class="content">
      <div class="login contact-form">
        {% if messages %}
        <h1>Thank you for contacting us</h1>
        <p class="lead">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
        </ul>
      </p>
      {% else %}
      <form class="login" id="contactForm" name="contactForm" autocomplete="off" novalidate action="/about-us/contact/add/" method="POST">
        {% csrf_token %}
        <h1>Contact us</h1>
        <p>
          <label for="first_name">Your name</label>
          <input type="text" name="first_name" id="first_name" placeholder="required" value="{{ form.first_name.value }}" required />
          {% if form.first_name.errors.0 %}
            <span class="alert alert-danger error-msg">{{ form.first_name.errors.0 }}</span>
          {% endif %}
        </p>
        <p>
          <label for="email">Email</label>
          <input type="text" name="email" id="email" placeholder="required" value="{{ form.email.value }}" required />
          {% if form.first_name.errors.0 %}
            <span class="email alert-danger error-msg">{{ form.email.errors.0 }}</span>
          {% endif %}
        </p>
        <p>
          <label for="email">Message</label>
          <textarea id="id_message" name="message" placeholder="required" rows="7" required>{{ form.message.value }}</textarea>
          {% if form.message.errors.0 %}
            <span class="alert alert-danger error-msg">{{ form.message.errors.0 }}</span>
          {% endif %}
        </p>
        <p>
          {{ form.captcha }}
          {% if form.captcha.errors.0 %}
            <span class="alert alert-danger error-msg special">{{ form.captcha.errors.0 }}</span>
          {% endif %}
        </p>
        <p class="indent">
          <input type="submit" name="submit" value="Submit" class="btn"/>
        </p>
      </form>
      {% endif %}
    </div>
  </div>
</div>
</section>
{% endif %}


{% endblock %}